### ISSUE TITLE
An error when feeding input samples

### ISSUE THREAD

**Issue by theanhle** [mmeendez8/Autoencoder#1]
There is an error in your implementation: Can 't feed input_holder (shape: [2, 14, 14]) into z (shape: (?, 10):

`Traceback (most recent call last):
  File "olala.py", line 185, in <module>
    artificial_image = sess.run(output, feed_dict={z: input_holder})
  File "/home/theanh/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/theanh/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 2) for Tensor 'Encoder/add:0', which has shape '(?, 10)'`

**Comment by mmeendez8** [comment]
This is not an error. If you check the README file you can see that one of the parameters it's related with the number of latent dimensions of the model:

 * latent_dim          Number of latent space dimensions

In the code this flat is set to 10:

`tf.flags.DEFINE_integer('latent_dim', 10, 'Number of latent dimensions')
`
So either change the default value or execute the program with:
`python autoencoder.py --latent_dim=2`

**Comment by theanhle** [comment]
I had changed before I notified you. Maybe I ran an incorrect command. Now, it works well. Thank for your quick response.
